create table final_project.posts
(
    id               int8 generated by default as identity,
    end_point        varchar(255),
    end_point_date   varchar(255),
    passengers       int8,
    start_point      varchar(255),
    start_point_date varchar(255),
    username         varchar(255),
    primary key (id)
);
create table final_project.roles
(
    id   int8 generated by default as identity,
    name varchar(20),
    primary key (id)
);
create table final_project.user_posts
(
    user_id int8 not null,
    post_id int8 not null,
    primary key (user_id, post_id)
);
create table final_project.user_roles
(
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id)
);
create table final_project.users
(
    id        int8 generated by default as identity,
    email     varchar(50),
    firstname varchar(50),
    gender    varchar(20),
    imageurl  varchar(255),
    lastname  varchar(50),
    password  varchar(120),
    phone     varchar(50),
    username  varchar(20),
    primary key (id)
);

alter table if exists final_project.users drop constraint if exists UKr43af9ap4edm43mmtq01oddj6;
alter table if exists final_project.users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table if exists final_project.users drop constraint if exists UK6dotkott2kjsp8vw4d0m25fb7;
alter table if exists final_project.users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists final_project.user_posts add constraint FK3idbfqdilj0glnid701fbbjp8 foreign key (post_id) references final_project.posts;
alter table if exists final_project.user_posts add constraint FK9spao74qxqjkns4i8h2r0kpnj foreign key (user_id) references final_project.users;
alter table if exists final_project.user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references final_project.roles;
alter table if exists final_project.user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references final_project.users;
